// Generated by Haxe 4.2.0
(function ($global) { "use strict";
var Main = function() { };
Main.main = function() {
	var anon = { x : 0.0, y : 0, z : "", w : new haxe_ds_StringMap(), p : [0], q : false, r : new Date()};
	Main.handle(anon);
};
Main.handle = function(anon) {
	console.log("discard/Main.hx:18:",anon.p);
	console.log("discard/Main.hx:19:",anon.q);
	console.log("discard/Main.hx:20:",anon.x);
	console.log("discard/Main.hx:21:",anon);
};
var haxe_ds_StringMap = function() {
	this.h = Object.create(null);
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
Main.main();
})({});
